### PR TITLE
Real-Debrid

### PR DESCRIPTION
**Pull request by edmundackah**
## Pull Request: Real-Debrid

**1. Please write a summary (bullet-point list) of the changes you have implemented:**

- Implemented RD.

<br>

**2. Do any of these changes rely on changes made to other repositories (e.g. CPlayer)?**  
_Delete where appropriate and specify the repositories._  

No

<br>

**3. Repositories (ignore if your answer to the previous question was 'No'):**
- CPlayer (https://github.com/ApolloTVofficial/cplayer)

<br>

## Standards Checklist
For more information, refer to [Wiki: Getting Started with Kamino](https://github.com/ApolloTVofficial/kamino/wiki/Getting-Started-with-Kamino).

- [x] My code uses _meaningful_ and correct variable names and **comments**.
- [x] My code follows Object-Oriented principles.
- [x] My code is, to the best of my ability, efficient and does not waste processor time.

### CODE REVIEW

**Comment by kevincosmos** [comment]
@edmundackah 

There are still a few outstanding issues before RD can be "fully implemented" (credits to @ddivad for the list):

1) the PR that is open needs the conflicts to be fixed before we can even think about merging it. 
2) The ability to play videos has to be added, it makes no sense saying RD is done without that.
3) It needs to be tested to see if we need to add more providers in Claws to actually serve links that RD can accept.
4) We need to discuss what's happening with the torrent scraper in the Kamino PR, as that shouldn't stay there (regardless of whether we drop cached torrent support or not)

Can you confirm that you are working on points 1 and 2?
Teekzilla and I will work together on finding more RD providers/resolvers (point 3)

**Comment by edmundackah** [comment]
@kevincosmos point 1 is out of my control as Sam is overhauling the UI. Until it gets finalised it will always be an issue. Point 2 once again UI is being worked on.

**Comment by kevincosmos** [comment]
@NBTX assigning this to you for movement :)

**Comment by NBTX** [comment]
@edmundackah could you remove `cplayer` from the PR?

**Pull request closed without merging**
