### PR TITLE
build.gradle: Comment out release config

### PR DESCRIPTION
**Pull request by SpajicM**
Noone is gonna release on their first ever build after clone, just get frustrated by the errors before they even started to contribute!

### CODE REVIEW

**Comment by edmundackah** [comment]
What if we want to test the release build locally?

**Comment by SpajicM** [comment]
Then you add it?

**Comment by edmundackah** [comment]
So why remove it in the first place?

**Comment by SpajicM** [comment]
Because keystore files are not there by default. Project should be pushed in buildable state out of the box.

**Comment by kevincosmos** [comment]
@NBTX @ddivad looping you in for opinions on this

**Comment by ddivad** [comment]
@edmundackah this pr is a good idea actually, as the massive majority of people who clone the project will want to run a dev build first, not release. Without having this commented out, the build will fail for a confusing reason and require more work for the users.

Reopening with this in mind, and I think it's something we should look into merging.

**Comment by NBTX** [comment]
Closing this PR but making the signing keys `debug` by default.

**Pull request closed without merging**
