### PR TITLE
Enable "Popular TV Shows" instead of "On The Air"

### PR DESCRIPTION
**Pull request by SpajicM**
"On The Air" are shows airing in the next 7 days, therefore none of those will have sources, rendering this tab mostly useless

Per discussion with @kevincosmos on Discord, this commit changes default settings to disable "On The Air" tab, and enabling "Popular TV Shows" instead.

### CODE REVIEW

**Comment by edmundackah** [comment]
We kept that tab as it is used my some to discover new shows

**Comment by SpajicM** [comment]
Then let's put "Airing Today" there instead

**Comment by kevincosmos** [comment]
My opinion:

It looks bad on us if we have a category on the home screen by default that 99% of the time will never yield a search result since the episode hasn't aired yet (although it can be used to watch previous episodes). I think a "Recently Aired" would make more sense than this, but IMO people are more likely to want "Popular TV Shows" by default to find shows that they might want to watch based on what other people are watching at the time.

**Comment by SpajicM** [comment]
@kevincosmos I don't see a "Recently Aired" endpoint in TMDB API.

It's then between "Popular TV Shows" and "Airing Today". Between the two, I'd say "Popular TV Shows" would be better, because "Airing Today" has it's own timezone trickery (described in more details in #110), adding to that the nature of our app, where shows mostly likely won't appear till few hours or a day later, which in the end could result in the same outcome as "On The Air" - no sources for the user.

**Comment by NBTX** [comment]
Should we include some code to automatically update your launchpad configuration if you've left it as the default?

**Comment by kevincosmos** [comment]
> Should we include some code to automatically update your launchpad configuration if you've left it as the default?

I think it would be alright to leave it as is - people can make the change manually if they want to

**Comment by SpajicM** [comment]
Popular TV Shows removed in https://github.com/ApolloTVofficial/kamino/commit/bcfc9da714fd53666823c9fa99ca14fcf3d08685#diff-f31da1eaf453feb2e3fc909d66813704L63

Closing PR.

**Pull request closed without merging**
