### PR TITLE
Client-side server support, added Base Claws vendor configuration.

### PR DESCRIPTION
**Pull request by j0j00**
## Pull Request: Client-side server support, added Base Claws vendor configuration.

**1. Please write a summary (bullet-point list) of the changes you have implemented:**

- Add base generic vendor configuration that interacts with the Claws server out of the box, it can be easily extended by passing in the appropriate variables, you can pass the client-side MicroServer support as a delegate class if you require it.
- Add basic client-side server scraper support, all of the scraper logic is in the `claws-client` directory.
    Set up step are as follows:
    - Follow the instructions in the `claws-client` directory, and generate the bundle files.
    - Pull the [liquidcore plugin](https://github.com/j0j00/flutter_liquidcore) submodule (once the iOS integration is done, I'll publish it, and it can be removed as a submodule).
    - Uncomment the `flutter_liquidcore` dependency in `pubspec.yaml`, and fetch the packages. 
     It was commented out because it adds about 27.5MB to the binary output, and I don't think there's an easy way to add optional dependencies in Flutter.
    - Use the sample configuration setup available [here](https://gist.github.com/j0j00/e71fc7c34a21b6c491260b734b82bc0e) as a guide for how to use it.
- Exclude .idea directory from version control.
- Add script for initializing the project (currently only generates the android keystore).
- Ignore i18n localization file from version control.

Although it's called a MicroServer, it doesn't actually run an http server, it just emits the events.

In terms of the iOS integration of Liquidcore, we can try generating the bulk of the Swift logic using https://github.com/elijah-z142/j2swift or https://github.com/eyob--/j2swift.

**2. Do any of these changes rely on changes made to other repositories (e.g. CPlayer)?**  

Yes

**3. Repositories (ignore if your answer to the previous question was 'No'):**
- Claws (https://github.com/ApolloTVofficial/Claws) - requires some environment variable changes so that the "scrape" events aren't sent when running in "client" mode.

### CODE REVIEW

**Comment by NBTX** [comment]
@edmundackah Yes. You can pull the code from @j0j00 's repository (**the `client-side-server` branch contains the changes.**), compile and run it.

**Comment by j0j00** [comment]
Recent changes:

- Add flutter_user_agent for setting the user agent to that of the device when making requests.
- Add the ability to disconnect/stop the API calls as soon as the user dismisses the loading alert box. This stops the weird issue with the video player popping up after the user cancels their search.
- Add `flutter_liquidcore` integration to the codebase (iOS will probably require running `pod update` to get it to compile.).
- Replace w3c_event_source with eventsource plugin due it leaking network resources when it's cancelled.
- Add official http client which uses the device's user agent for requests rather than "Dart/<dart_version> (dart:io)".
- Includes better error handling when errors occur during authentication, fetching links.

Unfortunately I won't be contributing any further to this project for the foreseeable future, so if there's any further merge conflicts stopping this from being merged in, I won't be able to fix them.

**Comment by SpajicM** [comment]
Is the setting for switching between server and client side scraping added?

**Comment by SamJakob** [comment]
Yes but it will need to be reimplemented due to changes to settings.

**Pull request merged**
