### PR TITLE
Update strings_nl.arb

### PR DESCRIPTION
**Pull request by Rowan-Paul**
## Pull Request: Update strings_nl.arb

**1. Please write a summary (bullet-point list) of the changes you have implemented:**

 - fixed a typo
 - better context aware translation
 - added new strings

<br>

**2. Do any of these changes rely on changes made to other repositories (e.g. CPlayer)?**  
_Delete where appropriate and specify the repositories._  

No

<br>

**3. Repositories (ignore if your answer to the previous question was 'No'):**
- CPlayer (https://github.com/ApolloTVofficial/cplayer)

<br>

## Standards Checklist
For more information, refer to [Wiki: Getting Started with Kamino](https://github.com/ApolloTVofficial/kamino/wiki/Getting-Started-with-Kamino).

- [x] My code uses _meaningful_ and correct variable names and **comments**.
- [x] My code follows Object-Oriented principles.
- [x] My code is, to the best of my ability, efficient and does not waste processor time.

### CODE REVIEW

**Comment by NBTX** [comment]
strings_nl.arb [FAIL]

```json
Comparing strings_nl.arb to strings_en.arb...
strings_nl.arb is missing the following translations:
They should be added to the bottom of the file.
	"x_found_in_y": "",
	"submit_request": "",
	"code_x": "",
	"you_can_log_into_realdebrid_in_two_ways": "",
	"if_youre_not_sure_what_these_options_are_just_use_login": "",
	"use_code": "",
	"login": "",
	"or": "",
	"enter_the_following_code": "",
	"visit_the_following_url_in_your_browser": "",
	"does_nothing_in_release_mode": "",
	"please_follow_the_instructions_shown_to_log_in_via_your_browser": "",
	"expires_in_x_daysOther": "",
	"expires_in_x_daysOne": "",
	"sorts_by_date_added": "",
	"date_added": "",
	"reviews_n": "",
	"reviews": ""
```

**Comment by Rowan-Paul** [comment]
"expires_in_x_days**Other**": "vervalt_in_x_daysAnders",
	"expires_in_x_days**One**": "vervalt_in_x_daysOne",

does **Other** and **One** need to be translated as well?

**Comment by NBTX** [comment]
Ah sorry, I didn't provide the English equivalents. You shouldn't be translating the keys as they are - it's just an automated test that tells you what keys to check.

One and Other on the end of the string tell it how to deal with plurals - this is mentioned in the documentation.

**Comment by Rowan-Paul** [comment]
Should be fixed now

**Pull request merged**
